---
title: "Final Project"
author: "Isa Ross"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

Load packages and raw elephant data

```{r}
library(tidyverse)
raw_data <- read_csv("../data_raw/all.data.final.csv")
```

## Cleaning Data

Rename and select columns of interest

```{r}
select_data <- raw_data %>%  #week3
    mutate(country = CountryName.x, #week6
         site = sitecode,
         ivory.price = ivory.price.toan, 
         num.poach = illegal,
         all.carcass = totcarc,
         perc.dead.poach = num.poach/all.carcass, #week2
         year = yr,
         perc.pop.poach = num.poach/ele.pop) %>% 
  select(country, site, site.area, year, all.carcass, num.poach, perc.dead.poach, perc.pop.poach, ele.pop, ele.density, ivory.price) %>% 
  drop_na(ivory.price) #week6
```

Categorize each site by size

```{r}
# weeks 12 & 13

area.size.sqkm <- vector("character", length = nrow(select_data))

for (i in 1:nrow(select_data)) {
  site.area <- select_data$site.area[i]
   if (site.area <= 10000) {
     area.size.sqkm[i] <- "tiny"
   } else if (site.area <= 20000) {
     area.size.sqkm[i] <- "small"
   } else if (site.area <= 30000) {
     area.size.sqkm[i] <- "medium"
   } else if (site.area <= 40000) {
     area.size.sqkm[i] <- "large"
   } else {
     area.size.sqkm[i] <- "huge"
   } 
  select_data$area.size.sqkm <- area.size.sqkm
}
```

Categorize each site by poaching density, determined by the number of elephants poached per km

```{r}
# week 11

poach_per_km <- function(dataframe) {
  dataframe$poach.density <- dataframe$num.poach / dataframe$site.area
  return(dataframe)
}

select_data <- poach_per_km(select_data)

# classify poaching level by poach_per_km

# explore poach.density range

range(select_data$poach.density)
max(select_data$poach.density)/5
min(select_data$poach.density)

select_data$poach.density<=0.05

poach.level <- vector("character", length = nrow(select_data))

select_data <- select_data %>% 
  mutate(poach.level = case_when(
    poach.density <= 0.005 ~ "miniscule",
    poach.density <= 0.01 ~ "low",
    poach.density <= 0.015 ~ "medium",
    poach.density <= 0.02 ~ "high",
    TRUE ~ "extreme"
  ))
```

Calculate and visualize mean poaching per km in each year

```{r}
# create a data frame with the mean poaching density for each year

annual_means <- select_data %>% 
  group_by(year) %>% 
  summarize(annual.mean.poach = mean(poach.density, na.rm = TRUE))

# join mean data into main data frame
# week 4

select_data <- select_data %>% 
  left_join(annual_means, by = "year")

# plot annual mean poaching by year

plot(select_data$year, select_data$annual.mean.poach,
     xlab = "Year", ylab = "Annual mean poach per km", 
     main = "Annual poach by year", pch = 16)

ggsave("Annual_poach_by_year.png", path = "../outputs/")
```

Sort poach density by country

```{r}
# create a data frame with the mean poaching density for each country

poach_by_country <- select_data %>% 
  group_by(country) %>% 
  summarize(mean.poach.country = mean(poach.density, na.rm = TRUE))

# join into main data frame

select_data <- select_data %>% 
  left_join(poach_by_country, by = "country")

# plot mean poaching by country

select_data %>% ggplot(aes(x = country, y = mean.poach.country)) +
  geom_point(color = "purple", size = 3)+
  xlab("Country") +
  ylab("Mean poach")+
  ggtitle("Mean poach by country")+
  theme_light()

ggsave("Poach_by_country.png", path = "../outputs/")
```

Plot annual poaching by country

```{r}
select_data %>% ggplot(aes(x = year, y = annual.mean.poach, color = country)) +
  geom_point()+
  facet_wrap(~ country)+
  xlab("Year") +
  ylab("Annual mean poach per km")+
  ggtitle("Annual poach by country")+
  theme_light()

ggsave("Annual_poach_by_country.png", path = "../outputs/")
```
